### ISSUE TITLE
Send Time And GPS From App to ELOC

### ISSUE THREAD

**Issue by EDsteve** [LIFsCode/ELOC-3.0#52]
@LIFsCode @OOHehir

I know i know. I am adding a lot of requests lately. Just trying to get the app and the recording working without issues before we are drunk in Christmas season :)

The ELOC does not get Time and GPS from the Android app yet. It's a crucial feature and needs to be impemented. We don't have a propper command for it yet.

The Android app should synch time with the ELOC: 
- With every BT connection (Every connection would be good, but setConfig only works if the LEOC is not recording/detecting, correct? That would be okay i think)

GPS should be sent:
- Every time recording/detecting starts

Separated command or should it be sent with setConfig?

About GPS:
In the old firmware from Tom we used [Open Location Codes](https://en.wikipedia.org/wiki/Open_Location_Code). More human friendly compared to Latitude and Longitude. Turned out it gave us more headache at the end because most software just uses Lat Long.
Would be great to keep Open Location Code but additionally add Lat and Long.

**Comment by LIFsCode** [comment]
I don't know what you mean with "red times" are that the timestamps before setTime command?
If yes then that's an unknown timestamp there is no way for the ELOC to know the time before setTime.

Due to [errenous delay](https://github.com/LIFsCode/ELOC-3.0/issues/13) in the Arduino libraries without initial time setting. The time after boot is set to the compile time, which is the last known valid time, but has no relation to the actual time.

The ELOC does not store multiple timezones all times are times in the current timezone. 
The time diff you showed in the screenshot shows difference in the modified timestamp this can occur if setTime is issued after the files are created.
But I cannot tell without log file.

I tried to reproduce this morning but no chance to get your effect. Can you please provide a log file?
