### ISSUE TITLE
Merging heapDebugging into master - please review 'sdkconfig.defaults' & 'nvs.csv'

### ISSUE THREAD

**Issue by OOHehir** [LIFsCode/ELOC-3.0#76]
@LIFsCode I believe I've merged most of the required from heapDebugging into master. When you get a chance could you please review the files below to see what you'd like to retain?
1. sdkconfig.defaults
2. nvs.csv

**Comment by LIFsCode** [comment]
@OOHehir Thanks for the merge.

I'm not sure how familiar you are with the[ git cherry-pick feature](https://www.atlassian.com/de/git/tutorials/cherry-pick). I guess this would be the more simple and clearer option for picking the important bugfix changes to master branch, but that's just for the future.

I added a [fix for starting the AI detection](https://github.com/LIFsCode/ELOC-3.0/commit/16d1f3c6c410e7cb91cede7f033c8ef53a21a8b2) that's all. The sdkconfig.defaults looks good. In the end we can discuss on which core we want to have the BT running.  Since this had no effect on the crashs we could keep it on core 0 which is under less load. But that's a story after the Release of the batch of ELOCs on thursday.

I also did a few tests today (also with extended heap poisoning) and didn't run into any crashs. 
@EDsteve Could you run your tests with [6d0dd72](https://github.com/LIFsCode/ELOC-3.0/commit/6d0dd7292d327adf257a466cfbdd93381ebecb6f) This is most likely the version to be released on the ELOCs.

I still have a few questions/remarks for this merge. But these are not for now, first let @EDsteve deploy the first batch of ELOCs and then we can start cleaning things up a bit:

1. You still [delete the EI Task ](https://github.com/LIFsCode/ELOC-3.0/blob/b5d2742662ac89dc57185522f0b1a5f68dc755f7/eloc610LowPowerPartition/src/EdgeImpulse.cpp#L193) which may be potentially harmfull if it is triggered via TaskNotify. Is there any reason for this? Because I guess since the system **must** support running recording & detection in parallel. We could also just leave the tasks created throughout the whole runtime. If the task is blocked via a `xTaskNotifyWait `or `xQueueReceive` with `portMAX_DELAY ` timeout the task will seldomly run and thus won't affect power consumption. Having the tasks created throughout the whole runtime also has a positive effect on heap fragmentation. Or what do you think about runtime static threads?
2. I must admit I don't get this commit [941e785](https://github.com/LIFsCode/ELOC-3.0/commit/941e78585071c73223a1e038906832bc53ec7098).  As I see it this commit has 2 parts:
- Changes in [I2SMEMSSampler.cpp](https://github.com/LIFsCode/ELOC-3.0/commit/941e78585071c73223a1e038906832bc53ec7098#diff-aa379d0945cd04f4207aa8f2834ef97a195689e2bd9738c82b1d7d19cad5cde2) --> not notiying the AI task when it's not running --> solves problem with a deleted task (see my point 1 here) That's the actual bugfix
- Changes in [main.cpp](https://github.com/LIFsCode/ELOC-3.0/commit/941e78585071c73223a1e038906832bc53ec7098#diff-fae1224ef719c87335eef5b5cdc7cc89512b927886ad697530875a8ba78cdce4): This does not make sense in my opinion. Using the intermediate variable before assigning the global should not affect execution behavior. Or if it does it is only in a random timing related behavior and thus not really stable. So in my opinion these changes could be reversed.
